raw_data_dir: data/raw
processed_data_path: data/processed/final-homicide-dataset.csv

datasets:
  - data/raw/economic-inequality-gini-index.csv
  - data/raw/gdp-per-capita-maddison-project-database.csv
  - data/raw/homicide-rate-unodc.csv
  - data/raw/human-development-index.csv
  - data/raw/political-corruption-index.csv
  - data/raw/rule-of-law-index.csv
  - data/raw/share-of-population-urban.csv